language: scala
scala:
- 2.11.4
script:
- sbt clean coverage test
before_install:
- openssl aes-256-cbc -K $encrypted_d4bcb24b4a82_key -iv $encrypted_d4bcb24b4a82_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
after_success:
- sbt coverageReport
- sbt coverageAggregate
- sbt codacyCoverage
