language: scala
scala:
- 2.11.6
script:
- sbt clean "project bitwatts-core" coverage test
after_success:
- sbt "project bitwatts-core" coverageReport
- sbt "project bitwatts-core" codacyCoverage
- sbt "project bitwatts-core" coveralls
